# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import wazo_appgateway_client
from wazo_appgateway_client.api.applications_api import ApplicationsApi  # noqa: E501
from wazo_appgateway_client.rest import ApiException


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self):
        self.api = wazo_appgateway_client.api.applications_api.ApplicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_applications_application_name_event_filter_put(self):
        """Test case for applications_application_name_event_filter_put

        Filter application events types.  # noqa: E501
        """
        pass

    def test_applications_application_name_get(self):
        """Test case for applications_application_name_get

        Get details of an application.  # noqa: E501
        """
        pass

    def test_applications_application_name_subscription_delete(self):
        """Test case for applications_application_name_subscription_delete

        Unsubscribe an application from an event source.  # noqa: E501
        """
        pass

    def test_applications_application_name_subscription_post(self):
        """Test case for applications_application_name_subscription_post

        Subscribe an application to a event source.  # noqa: E501
        """
        pass

    def test_applications_get(self):
        """Test case for applications_get

        List all applications.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
