# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import wazo_appgateway_client
from wazo_appgateway_client.models.rt_pstat import RTPstat  # noqa: E501
from wazo_appgateway_client.rest import ApiException

class TestRTPstat(unittest.TestCase):
    """RTPstat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RTPstat
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = wazo_appgateway_client.models.rt_pstat.RTPstat()  # noqa: E501
        if include_optional :
            return RTPstat(
                channel_uniqueid = '0', 
                local_maxjitter = 1.337, 
                local_maxrxploss = 1.337, 
                local_minjitter = 1.337, 
                local_minrxploss = 1.337, 
                local_normdevjitter = 1.337, 
                local_normdevrxploss = 1.337, 
                local_ssrc = 56, 
                local_stdevjitter = 1.337, 
                local_stdevrxploss = 1.337, 
                maxrtt = 1.337, 
                minrtt = 1.337, 
                normdevrtt = 1.337, 
                remote_maxjitter = 1.337, 
                remote_maxrxploss = 1.337, 
                remote_minjitter = 1.337, 
                remote_minrxploss = 1.337, 
                remote_normdevjitter = 1.337, 
                remote_normdevrxploss = 1.337, 
                remote_ssrc = 56, 
                remote_stdevjitter = 1.337, 
                remote_stdevrxploss = 1.337, 
                rtt = 1.337, 
                rxcount = 56, 
                rxjitter = 1.337, 
                rxoctetcount = 56, 
                rxploss = 56, 
                stdevrtt = 1.337, 
                txcount = 56, 
                txjitter = 1.337, 
                txoctetcount = 56, 
                txploss = 56
            )
        else :
            return RTPstat(
                channel_uniqueid = '0',
                local_ssrc = 56,
                remote_ssrc = 56,
                rxcount = 56,
                rxoctetcount = 56,
                rxploss = 56,
                txcount = 56,
                txoctetcount = 56,
                txploss = 56,
        )

    def testRTPstat(self):
        """Test RTPstat"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
