# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import wazo_appgateway_client
from wazo_appgateway_client.models.build_info import BuildInfo  # noqa: E501
from wazo_appgateway_client.rest import ApiException

class TestBuildInfo(unittest.TestCase):
    """BuildInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BuildInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = wazo_appgateway_client.models.build_info.BuildInfo()  # noqa: E501
        if include_optional :
            return BuildInfo(
                date = '0', 
                kernel = '0', 
                machine = '0', 
                options = '0', 
                os = '0', 
                user = '0'
            )
        else :
            return BuildInfo(
                date = '0',
                kernel = '0',
                machine = '0',
                options = '0',
                os = '0',
                user = '0',
        )

    def testBuildInfo(self):
        """Test BuildInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
