# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import wazo_appgateway_client
from wazo_appgateway_client.api.events_api import EventsApi  # noqa: E501
from wazo_appgateway_client.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = wazo_appgateway_client.api.events_api.EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_events_get(self):
        """Test case for events_get

        WebSocket connection for events.  # noqa: E501
        """
        pass

    def test_events_user_event_name_post(self):
        """Test case for events_user_event_name_post

        Generate a user event.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
