# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import wazo_appgateway_client
from wazo_appgateway_client.api.playbacks_api import PlaybacksApi  # noqa: E501
from wazo_appgateway_client.rest import ApiException


class TestPlaybacksApi(unittest.TestCase):
    """PlaybacksApi unit test stubs"""

    def setUp(self):
        self.api = wazo_appgateway_client.api.playbacks_api.PlaybacksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_playbacks_playback_id_control_post(self):
        """Test case for playbacks_playback_id_control_post

        Control a playback.  # noqa: E501
        """
        pass

    def test_playbacks_playback_id_delete(self):
        """Test case for playbacks_playback_id_delete

        Stop a playback.  # noqa: E501
        """
        pass

    def test_playbacks_playback_id_get(self):
        """Test case for playbacks_playback_id_get

        Get a playback's details.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
