# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import wazo_appgateway_client
from wazo_appgateway_client.models.sound import Sound  # noqa: E501
from wazo_appgateway_client.rest import ApiException

class TestSound(unittest.TestCase):
    """Sound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Sound
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = wazo_appgateway_client.models.sound.Sound()  # noqa: E501
        if include_optional :
            return Sound(
                formats = [
                    wazo_appgateway_client.models.format_lang_pair.FormatLangPair(
                        format = '0', 
                        language = '0', )
                    ], 
                id = '0', 
                text = '0'
            )
        else :
            return Sound(
                formats = [
                    wazo_appgateway_client.models.format_lang_pair.FormatLangPair(
                        format = '0', 
                        language = '0', )
                    ],
                id = '0',
        )

    def testSound(self):
        """Test Sound"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
