# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import wazo_appgateway_client
from wazo_appgateway_client.models.config_info import ConfigInfo  # noqa: E501
from wazo_appgateway_client.rest import ApiException

class TestConfigInfo(unittest.TestCase):
    """ConfigInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ConfigInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = wazo_appgateway_client.models.config_info.ConfigInfo()  # noqa: E501
        if include_optional :
            return ConfigInfo(
                default_language = '0', 
                max_channels = 56, 
                max_load = 1.337, 
                max_open_files = 56, 
                name = '0', 
                setid = wazo_appgateway_client.models.set_id.SetId(
                    group = '0', 
                    user = '0', )
            )
        else :
            return ConfigInfo(
                default_language = '0',
                name = '0',
                setid = wazo_appgateway_client.models.set_id.SetId(
                    group = '0', 
                    user = '0', ),
        )

    def testConfigInfo(self):
        """Test ConfigInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
