# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import wazo_appgateway_client
from wazo_appgateway_client.models.channel_destroyed_all_of import ChannelDestroyedAllOf  # noqa: E501
from wazo_appgateway_client.rest import ApiException

class TestChannelDestroyedAllOf(unittest.TestCase):
    """ChannelDestroyedAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ChannelDestroyedAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = wazo_appgateway_client.models.channel_destroyed_all_of.ChannelDestroyedAllOf()  # noqa: E501
        if include_optional :
            return ChannelDestroyedAllOf(
                cause = 56, 
                cause_txt = '0', 
                channel = wazo_appgateway_client.models.channel.Channel(
                    accountcode = '0', 
                    caller = wazo_appgateway_client.models.caller_id.CallerID(
                        name = '0', 
                        number = '0', ), 
                    channelvars = wazo_appgateway_client.models.channelvars.channelvars(), 
                    connected = wazo_appgateway_client.models.caller_id.CallerID(
                        name = '0', 
                        number = '0', ), 
                    creationtime = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    dialplan = wazo_appgateway_client.models.dialplan_cep.DialplanCEP(
                        app_data = '0', 
                        app_name = '0', 
                        context = '0', 
                        exten = '0', 
                        priority = 56, ), 
                    id = '0', 
                    language = '0', 
                    name = '0', 
                    state = '0', )
            )
        else :
            return ChannelDestroyedAllOf(
                cause = 56,
                cause_txt = '0',
                channel = wazo_appgateway_client.models.channel.Channel(
                    accountcode = '0', 
                    caller = wazo_appgateway_client.models.caller_id.CallerID(
                        name = '0', 
                        number = '0', ), 
                    channelvars = wazo_appgateway_client.models.channelvars.channelvars(), 
                    connected = wazo_appgateway_client.models.caller_id.CallerID(
                        name = '0', 
                        number = '0', ), 
                    creationtime = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    dialplan = wazo_appgateway_client.models.dialplan_cep.DialplanCEP(
                        app_data = '0', 
                        app_name = '0', 
                        context = '0', 
                        exten = '0', 
                        priority = 56, ), 
                    id = '0', 
                    language = '0', 
                    name = '0', 
                    state = '0', ),
        )

    def testChannelDestroyedAllOf(self):
        """Test ChannelDestroyedAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
