# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import wazo_appgateway_client
from wazo_appgateway_client.models.asterisk_info import AsteriskInfo  # noqa: E501
from wazo_appgateway_client.rest import ApiException

class TestAsteriskInfo(unittest.TestCase):
    """AsteriskInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AsteriskInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = wazo_appgateway_client.models.asterisk_info.AsteriskInfo()  # noqa: E501
        if include_optional :
            return AsteriskInfo(
                build = wazo_appgateway_client.models.build_info.BuildInfo(
                    date = '0', 
                    kernel = '0', 
                    machine = '0', 
                    options = '0', 
                    os = '0', 
                    user = '0', ), 
                config = wazo_appgateway_client.models.config_info.ConfigInfo(
                    default_language = '0', 
                    max_channels = 56, 
                    max_load = 1.337, 
                    max_open_files = 56, 
                    name = '0', 
                    setid = wazo_appgateway_client.models.set_id.SetId(
                        group = '0', 
                        user = '0', ), ), 
                status = wazo_appgateway_client.models.status_info.StatusInfo(
                    last_reload_time = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    startup_time = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                system = wazo_appgateway_client.models.system_info.SystemInfo(
                    entity_id = '0', 
                    version = '0', )
            )
        else :
            return AsteriskInfo(
        )

    def testAsteriskInfo(self):
        """Test AsteriskInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
