# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from wazo_appgateway_client.configuration import Configuration


class BuildInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'date': 'str',
        'kernel': 'str',
        'machine': 'str',
        'options': 'str',
        'os': 'str',
        'user': 'str'
    }

    attribute_map = {
        'date': 'date',
        'kernel': 'kernel',
        'machine': 'machine',
        'options': 'options',
        'os': 'os',
        'user': 'user'
    }

    def __init__(self, date=None, kernel=None, machine=None, options=None, os=None, user=None, local_vars_configuration=None):  # noqa: E501
        """BuildInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._date = None
        self._kernel = None
        self._machine = None
        self._options = None
        self._os = None
        self._user = None
        self.discriminator = None

        self.date = date
        self.kernel = kernel
        self.machine = machine
        self.options = options
        self.os = os
        self.user = user

    @property
    def date(self):
        """Gets the date of this BuildInfo.  # noqa: E501

        Date and time when Asterisk was built.  # noqa: E501

        :return: The date of this BuildInfo.  # noqa: E501
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this BuildInfo.

        Date and time when Asterisk was built.  # noqa: E501

        :param date: The date of this BuildInfo.  # noqa: E501
        :type date: str
        """
        if self.local_vars_configuration.client_side_validation and date is None:  # noqa: E501
            raise ValueError("Invalid value for `date`, must not be `None`")  # noqa: E501

        self._date = date

    @property
    def kernel(self):
        """Gets the kernel of this BuildInfo.  # noqa: E501

        Kernel version Asterisk was built on.  # noqa: E501

        :return: The kernel of this BuildInfo.  # noqa: E501
        :rtype: str
        """
        return self._kernel

    @kernel.setter
    def kernel(self, kernel):
        """Sets the kernel of this BuildInfo.

        Kernel version Asterisk was built on.  # noqa: E501

        :param kernel: The kernel of this BuildInfo.  # noqa: E501
        :type kernel: str
        """
        if self.local_vars_configuration.client_side_validation and kernel is None:  # noqa: E501
            raise ValueError("Invalid value for `kernel`, must not be `None`")  # noqa: E501

        self._kernel = kernel

    @property
    def machine(self):
        """Gets the machine of this BuildInfo.  # noqa: E501

        Machine architecture (x86_64, i686, ppc, etc.)  # noqa: E501

        :return: The machine of this BuildInfo.  # noqa: E501
        :rtype: str
        """
        return self._machine

    @machine.setter
    def machine(self, machine):
        """Sets the machine of this BuildInfo.

        Machine architecture (x86_64, i686, ppc, etc.)  # noqa: E501

        :param machine: The machine of this BuildInfo.  # noqa: E501
        :type machine: str
        """
        if self.local_vars_configuration.client_side_validation and machine is None:  # noqa: E501
            raise ValueError("Invalid value for `machine`, must not be `None`")  # noqa: E501

        self._machine = machine

    @property
    def options(self):
        """Gets the options of this BuildInfo.  # noqa: E501

        Compile time options, or empty string if default.  # noqa: E501

        :return: The options of this BuildInfo.  # noqa: E501
        :rtype: str
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this BuildInfo.

        Compile time options, or empty string if default.  # noqa: E501

        :param options: The options of this BuildInfo.  # noqa: E501
        :type options: str
        """
        if self.local_vars_configuration.client_side_validation and options is None:  # noqa: E501
            raise ValueError("Invalid value for `options`, must not be `None`")  # noqa: E501

        self._options = options

    @property
    def os(self):
        """Gets the os of this BuildInfo.  # noqa: E501

        OS Asterisk was built on.  # noqa: E501

        :return: The os of this BuildInfo.  # noqa: E501
        :rtype: str
        """
        return self._os

    @os.setter
    def os(self, os):
        """Sets the os of this BuildInfo.

        OS Asterisk was built on.  # noqa: E501

        :param os: The os of this BuildInfo.  # noqa: E501
        :type os: str
        """
        if self.local_vars_configuration.client_side_validation and os is None:  # noqa: E501
            raise ValueError("Invalid value for `os`, must not be `None`")  # noqa: E501

        self._os = os

    @property
    def user(self):
        """Gets the user of this BuildInfo.  # noqa: E501

        Username that build Asterisk  # noqa: E501

        :return: The user of this BuildInfo.  # noqa: E501
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this BuildInfo.

        Username that build Asterisk  # noqa: E501

        :param user: The user of this BuildInfo.  # noqa: E501
        :type user: str
        """
        if self.local_vars_configuration.client_side_validation and user is None:  # noqa: E501
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BuildInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BuildInfo):
            return True

        return self.to_dict() != other.to_dict()
