# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from wazo_appgateway_client.configuration import Configuration


class ChannelHangupRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cause': 'int',
        'channel': 'Channel',
        'soft': 'bool'
    }

    attribute_map = {
        'cause': 'cause',
        'channel': 'channel',
        'soft': 'soft'
    }

    def __init__(self, cause=None, channel=None, soft=None, local_vars_configuration=None):  # noqa: E501
        """ChannelHangupRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._cause = None
        self._channel = None
        self._soft = None
        self.discriminator = None

        if cause is not None:
            self.cause = cause
        self.channel = channel
        if soft is not None:
            self.soft = soft

    @property
    def cause(self):
        """Gets the cause of this ChannelHangupRequest.  # noqa: E501

        Integer representation of the cause of the hangup.  # noqa: E501

        :return: The cause of this ChannelHangupRequest.  # noqa: E501
        :rtype: int
        """
        return self._cause

    @cause.setter
    def cause(self, cause):
        """Sets the cause of this ChannelHangupRequest.

        Integer representation of the cause of the hangup.  # noqa: E501

        :param cause: The cause of this ChannelHangupRequest.  # noqa: E501
        :type cause: int
        """

        self._cause = cause

    @property
    def channel(self):
        """Gets the channel of this ChannelHangupRequest.  # noqa: E501


        :return: The channel of this ChannelHangupRequest.  # noqa: E501
        :rtype: Channel
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this ChannelHangupRequest.


        :param channel: The channel of this ChannelHangupRequest.  # noqa: E501
        :type channel: Channel
        """
        if self.local_vars_configuration.client_side_validation and channel is None:  # noqa: E501
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def soft(self):
        """Gets the soft of this ChannelHangupRequest.  # noqa: E501

        Whether the hangup request was a soft hangup request.  # noqa: E501

        :return: The soft of this ChannelHangupRequest.  # noqa: E501
        :rtype: bool
        """
        return self._soft

    @soft.setter
    def soft(self, soft):
        """Sets the soft of this ChannelHangupRequest.

        Whether the hangup request was a soft hangup request.  # noqa: E501

        :param soft: The soft of this ChannelHangupRequest.  # noqa: E501
        :type soft: bool
        """

        self._soft = soft

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChannelHangupRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ChannelHangupRequest):
            return True

        return self.to_dict() != other.to_dict()
