# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from wazo_appgateway_client.configuration import Configuration


class LogChannel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'channel': 'str',
        'configuration': 'str',
        'status': 'str',
        'type': 'str'
    }

    attribute_map = {
        'channel': 'channel',
        'configuration': 'configuration',
        'status': 'status',
        'type': 'type'
    }

    def __init__(self, channel=None, configuration=None, status=None, type=None, local_vars_configuration=None):  # noqa: E501
        """LogChannel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._channel = None
        self._configuration = None
        self._status = None
        self._type = None
        self.discriminator = None

        self.channel = channel
        self.configuration = configuration
        self.status = status
        self.type = type

    @property
    def channel(self):
        """Gets the channel of this LogChannel.  # noqa: E501

        The log channel path  # noqa: E501

        :return: The channel of this LogChannel.  # noqa: E501
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this LogChannel.

        The log channel path  # noqa: E501

        :param channel: The channel of this LogChannel.  # noqa: E501
        :type channel: str
        """
        if self.local_vars_configuration.client_side_validation and channel is None:  # noqa: E501
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def configuration(self):
        """Gets the configuration of this LogChannel.  # noqa: E501

        The various log levels  # noqa: E501

        :return: The configuration of this LogChannel.  # noqa: E501
        :rtype: str
        """
        return self._configuration

    @configuration.setter
    def configuration(self, configuration):
        """Sets the configuration of this LogChannel.

        The various log levels  # noqa: E501

        :param configuration: The configuration of this LogChannel.  # noqa: E501
        :type configuration: str
        """
        if self.local_vars_configuration.client_side_validation and configuration is None:  # noqa: E501
            raise ValueError("Invalid value for `configuration`, must not be `None`")  # noqa: E501

        self._configuration = configuration

    @property
    def status(self):
        """Gets the status of this LogChannel.  # noqa: E501

        Whether or not a log type is enabled  # noqa: E501

        :return: The status of this LogChannel.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this LogChannel.

        Whether or not a log type is enabled  # noqa: E501

        :param status: The status of this LogChannel.  # noqa: E501
        :type status: str
        """
        if self.local_vars_configuration.client_side_validation and status is None:  # noqa: E501
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def type(self):
        """Gets the type of this LogChannel.  # noqa: E501

        Types of logs for the log channel  # noqa: E501

        :return: The type of this LogChannel.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LogChannel.

        Types of logs for the log channel  # noqa: E501

        :param type: The type of this LogChannel.  # noqa: E501
        :type type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LogChannel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LogChannel):
            return True

        return self.to_dict() != other.to_dict()
