# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from wazo_appgateway_client.configuration import Configuration


class Mailbox(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'new_messages': 'int',
        'old_messages': 'int'
    }

    attribute_map = {
        'name': 'name',
        'new_messages': 'new_messages',
        'old_messages': 'old_messages'
    }

    def __init__(self, name=None, new_messages=None, old_messages=None, local_vars_configuration=None):  # noqa: E501
        """Mailbox - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._new_messages = None
        self._old_messages = None
        self.discriminator = None

        self.name = name
        self.new_messages = new_messages
        self.old_messages = old_messages

    @property
    def name(self):
        """Gets the name of this Mailbox.  # noqa: E501

        Name of the mailbox.  # noqa: E501

        :return: The name of this Mailbox.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Mailbox.

        Name of the mailbox.  # noqa: E501

        :param name: The name of this Mailbox.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def new_messages(self):
        """Gets the new_messages of this Mailbox.  # noqa: E501

        Count of new messages in the mailbox.  # noqa: E501

        :return: The new_messages of this Mailbox.  # noqa: E501
        :rtype: int
        """
        return self._new_messages

    @new_messages.setter
    def new_messages(self, new_messages):
        """Sets the new_messages of this Mailbox.

        Count of new messages in the mailbox.  # noqa: E501

        :param new_messages: The new_messages of this Mailbox.  # noqa: E501
        :type new_messages: int
        """
        if self.local_vars_configuration.client_side_validation and new_messages is None:  # noqa: E501
            raise ValueError("Invalid value for `new_messages`, must not be `None`")  # noqa: E501

        self._new_messages = new_messages

    @property
    def old_messages(self):
        """Gets the old_messages of this Mailbox.  # noqa: E501

        Count of old messages in the mailbox.  # noqa: E501

        :return: The old_messages of this Mailbox.  # noqa: E501
        :rtype: int
        """
        return self._old_messages

    @old_messages.setter
    def old_messages(self, old_messages):
        """Sets the old_messages of this Mailbox.

        Count of old messages in the mailbox.  # noqa: E501

        :param old_messages: The old_messages of this Mailbox.  # noqa: E501
        :type old_messages: int
        """
        if self.local_vars_configuration.client_side_validation and old_messages is None:  # noqa: E501
            raise ValueError("Invalid value for `old_messages`, must not be `None`")  # noqa: E501

        self._old_messages = old_messages

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Mailbox):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Mailbox):
            return True

        return self.to_dict() != other.to_dict()
