# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 5.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from wazo_appgateway_client.configuration import Configuration


class PeerStatusChangeAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'endpoint': 'Endpoint',
        'peer': 'Peer'
    }

    attribute_map = {
        'endpoint': 'endpoint',
        'peer': 'peer'
    }

    def __init__(self, endpoint=None, peer=None, local_vars_configuration=None):  # noqa: E501
        """PeerStatusChangeAllOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._endpoint = None
        self._peer = None
        self.discriminator = None

        self.endpoint = endpoint
        self.peer = peer

    @property
    def endpoint(self):
        """Gets the endpoint of this PeerStatusChangeAllOf.  # noqa: E501


        :return: The endpoint of this PeerStatusChangeAllOf.  # noqa: E501
        :rtype: Endpoint
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """Sets the endpoint of this PeerStatusChangeAllOf.


        :param endpoint: The endpoint of this PeerStatusChangeAllOf.  # noqa: E501
        :type endpoint: Endpoint
        """
        if self.local_vars_configuration.client_side_validation and endpoint is None:  # noqa: E501
            raise ValueError("Invalid value for `endpoint`, must not be `None`")  # noqa: E501

        self._endpoint = endpoint

    @property
    def peer(self):
        """Gets the peer of this PeerStatusChangeAllOf.  # noqa: E501


        :return: The peer of this PeerStatusChangeAllOf.  # noqa: E501
        :rtype: Peer
        """
        return self._peer

    @peer.setter
    def peer(self, peer):
        """Sets the peer of this PeerStatusChangeAllOf.


        :param peer: The peer of this PeerStatusChangeAllOf.  # noqa: E501
        :type peer: Peer
        """
        if self.local_vars_configuration.client_side_validation and peer is None:  # noqa: E501
            raise ValueError("Invalid value for `peer`, must not be `None`")  # noqa: E501

        self._peer = peer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PeerStatusChangeAllOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PeerStatusChangeAllOf):
            return True

        return self.to_dict() != other.to_dict()
